---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - java_se
  - name: alt_home
    run_list:
      - java_se
    excludes:
      - macosx-10
    attributes:
      java_se:
        java_home:
          C:\my\java\jdk
